### ISSUE TITLE
Does ths support postgis?

### ISSUE THREAD

**Issue by yh371174229** [marauder-io/tyler#6]
I have some questions：
1. Does ths support postgis?
2. I have more than 10 million polygon features in my vector layer which stored in postgresql，I want to render them on the fly，Now I use tilestrata ,but I think it's not fast as I think. I want to know use tyler weather can solve my problem?

Any help will appreciated，hope to receive your reply！

**Comment by f7o** [comment]
We do not support PostGIS. As rendering on demand using vector tiles has its limitations using PostGIS we have components using distributed databases able to render millions of geometries. These solutions are not open source.

The Tyler actually creates all vector tiles and stores these. So, this is not a real on the fly solution. Of course one could try to keep a PostGIS database in sync with the Tyler's vector tile storage.
